
package Validation.pos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PosTaggerRoWS", targetNamespace = "http://webPosRo.uaic/", wsdlLocation = "file:/C:/Users/mariu/test/PosTaggerRoWS.xml")
public class PosTaggerRoWS_Service
    extends Service
{

    private final static URL POSTAGGERROWS_WSDL_LOCATION;
    private final static WebServiceException POSTAGGERROWS_EXCEPTION;
    private final static QName POSTAGGERROWS_QNAME = new QName("http://webPosRo.uaic/", "PosTaggerRoWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/mariu/test/PosTaggerRoWS.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POSTAGGERROWS_WSDL_LOCATION = url;
        POSTAGGERROWS_EXCEPTION = e;
    }

    public PosTaggerRoWS_Service() {
        super(__getWsdlLocation(), POSTAGGERROWS_QNAME);
    }

    public PosTaggerRoWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), POSTAGGERROWS_QNAME, features);
    }

    public PosTaggerRoWS_Service(URL wsdlLocation) {
        super(wsdlLocation, POSTAGGERROWS_QNAME);
    }

    public PosTaggerRoWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POSTAGGERROWS_QNAME, features);
    }

    public PosTaggerRoWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PosTaggerRoWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PosTaggerRoWS
     */
    @WebEndpoint(name = "PosTaggerRoWSPort")
    public PosTaggerRoWS getPosTaggerRoWSPort() {
        return super.getPort(new QName("http://webPosRo.uaic/", "PosTaggerRoWSPort"), PosTaggerRoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PosTaggerRoWS
     */
    @WebEndpoint(name = "PosTaggerRoWSPort")
    public PosTaggerRoWS getPosTaggerRoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webPosRo.uaic/", "PosTaggerRoWSPort"), PosTaggerRoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POSTAGGERROWS_EXCEPTION!= null) {
            throw POSTAGGERROWS_EXCEPTION;
        }
        return POSTAGGERROWS_WSDL_LOCATION;
    }

}
